= Solutions Engineering Template Repository
A template repository that contains all required files (LICENSE, SUPPORT, CONTRIBUTING, etc) as outlined in the org standards.  

== Overview
This is a workshop to explore kubernetes and docker. 
This workshop will use Docker and KIND

== Getting Started
The lab are separate and each one will have a folder associated with the tasks. 

== Installation
We are using UDF, and it is self contained. We are using CentOS 7 with Desktop configuration for this workshop. 

== Community Code of Conduct
Please refer to the [F5 DevCentral Community Code of Conduct]<<code_of_conduct.adoc#,Code of Conduct>>.


== License
[Apache License 2.0](LICENSE)

== Copyright
Copyright 2014-2020 F5 Networks Inc.


=== F5 Networks Contributor License Agreement

Before you start contributing to any project sponsored by F5 Networks, Inc. (F5) on GitHub, you will need to sign a Contributor License Agreement (CLA).

If you are signing as an individual, we recommend that you talk to your employer (if applicable) before signing the CLA since some employment agreements may have restrictions on your contributions to other projects.
Otherwise by submitting a CLA you represent that you are legally entitled to grant the licenses recited therein.

If your employer has rights to intellectual property that you create, such as your contributions, you represent that you have received permission to make contributions on behalf of that employer, that your employer has waived such rights for your contributions, or that your employer has executed a separate CLA with F5.

If you are signing on behalf of a company, you represent that you are legally entitled to grant the license recited therein.
You represent further that each employee of the entity that submits contributions is authorized to submit such contributions on behalf of the entity pursuant to the CLA.
